name: Test
on: [push]

strategy:
  matrix:
    node-version: ['14.x', '16.x', '18.x']

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
          - name: Use Node.js ${{ matrix.node-version }}
            uses: actions/setup-node@v3
            with:
              node-version: ${{ matrix.node-version }}
          - name: Install pnpm
            uses: pnpm/action-setup@v2
            with:
              version: 8
              run_install: true
          - run: pnpm test


